name: netflix_portfolio
description: Netflix-style portfolio website for Vaibhav Shukla

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    # - assets/images/
    # - assets/icons/
    
  # fonts:
  #   - family: Netflix
  #     fonts:
  #       - asset: assets/fonts/NetflixSans-Regular.ttf
  #       - asset: assets/fonts/NetflixSans-Bold.ttf
  #         weight: 700